name: ranking-api-project

networks:
  ranking-api-net:
    driver: bridge

volumes:
  dynamodb:
    external: true

services:
    ranking-api:
      build:
        context: . # Directory containing the Dockerfile
        dockerfile: Dockerfile
      container_name: ranking-api
      ports:
        - "8080:8080"
      environment:
        - DYNAMODB_ENDPOINT=http://dynamodb-local:8000
      depends_on:
        - dynamodb-local
      networks:
        - ranking-api-net
    dynamodb-local:
      command: "-jar DynamoDBLocal.jar -sharedDb -dbPath /home/dynamodblocal/data"
      image: "amazon/dynamodb-local:latest"
      container_name: dynamodb-local
      user: root # Requires root user to avoid ‘unable to open database file’ error when using Volume
      ports:
        - "8000:8000"
      volumes:
        - dynamodb:/home/dynamodblocal/data
      working_dir: /home/dynamodblocal
      networks:
        - ranking-api-net

    dynamodb:
      image: "aaronshaf/dynamodb-admin"
      container_name: dynamodb-admin
      depends_on:
        - dynamodb-local
      ports:
        - "8001:8001"
      environment:
        - DYNAMO_ENDPOINT=http://dynamodb-local:8000
      networks:
        - ranking-api-net
